# Generated by Django 3.2 on 2021-05-09 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huyen',
            fields=[
                ('MaHuyen', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenHuyen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'HUYEN',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenKH', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(max_length=100)),
                ('SDT', models.CharField(max_length=11)),
                ('Pass', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('Login', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'KHACHHANG',
            },
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('MaTinh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenTinh', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TINH',
            },
        ),
        migrations.CreateModel(
            name='VanChuyen',
            fields=[
                ('MaKV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Gia', models.BigIntegerField()),
            ],
            options={
                'db_table': 'VANCHUYEN',
            },
        ),
        migrations.CreateModel(
            name='Xa',
            fields=[
                ('MaXa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenXa', models.CharField(max_length=100)),
                ('MaHuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.huyen')),
            ],
            options={
                'db_table': 'XA',
            },
        ),
        migrations.DeleteModel(
            name='accounttb',
        ),
        migrations.AddField(
            model_name='tinh',
            name='MaKV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vanchuyen'),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='MaXa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.xa'),
        ),
        migrations.AddField(
            model_name='huyen',
            name='MaTinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tinh'),
        ),
    ]
