# Generated by Django 3.2 on 2021-05-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_khoanggia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KhoangGia',
        ),
    ]
