# Generated by Django 3.2 on 2021-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210510_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('MaLH', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('SDT', models.CharField(max_length=11)),
                ('NoiDung', models.CharField(max_length=500)),
            ],
        ),
    ]
