# Generated by Django 3.2 on 2021-05-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lienhe'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lienhe',
            table='lienhe',
        ),
    ]
