# Generated by Django 3.2 on 2021-05-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ChiTietCM',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='MoTa',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='thuonghieu',
            name='MoTa',
            field=models.CharField(max_length=2000),
        ),
    ]
