# Generated by Django 3.2 on 2021-05-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210509_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='SoLuong',
            field=models.IntegerField(null=True),
        ),
    ]
