# Generated by Django 3.2 on 2021-05-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sanpham_soluong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='SoLuong',
            field=models.IntegerField(),
        ),
    ]
