# Generated by Django 3.2 on 2021-05-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_sanpham_soluong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KhoHang',
        ),
    ]
