# Generated by Django 3.2 on 2021-05-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_khoanggia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapXep',
            fields=[
                ('MaSX', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenSX', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SAPXEP',
            },
        ),
    ]
