# Generated by Django 3.2 on 2021-05-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_sapxep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapxep',
            name='MaSX',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
