# Generated by Django 3.2 on 2021-05-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210513_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='MaCM',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
