# Generated by Django 3.2 on 2021-05-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_delete_khohang'),
        ('core', '0002_auto_20210509_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NgayThanhToan', models.DateField()),
                ('ThanhTien', models.BigIntegerField()),
                ('DiaChiGH', models.CharField(max_length=100)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.khachhang')),
                ('MaXaGH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.xa')),
            ],
            options={
                'db_table': 'HOADON',
            },
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('MaCTHD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('GiaBan', models.BigIntegerField()),
                ('SoLuong', models.BigIntegerField()),
                ('MaHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccount.hoadon')),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sanpham')),
            ],
            options={
                'db_table': 'CHITIETHOADON',
            },
        ),
    ]
