# Generated by Django 3.2 on 2021-05-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_alter_hoadon_ngaythanhtoan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoadon',
            old_name='NgayThanhToan',
            new_name='NgayDatHang',
        ),
    ]
