# Generated by Django 3.2 on 2021-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_rename_ngaythanhtoan_hoadon_ngaydathang'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='DiaChiNhan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='SDTNgNhan',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='TenNgNhan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
