# Generated by Django 3.2 on 2021-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_auto_20210512_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='VanChuyen',
            field=models.BigIntegerField(default=98000),
        ),
    ]
