# Generated by Django 3.2 on 2021-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_hoadon_vanchuyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='VanChuyen',
            field=models.BigIntegerField(),
        ),
    ]
