# Generated by Django 3.2 on 2021-05-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0007_alter_hoadon_vanchuyen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='DiaChiGH',
        ),
    ]
